version: '3.9'

services:
  backend:
    build:
      context: backend
      target: development
    command: air
    volumes:
      - ./backend:/go/src/github.com/koyashiro/postgres-playground

  frontend:
    build:
      context: frontend
      target: development
    command: aleph dev --host 0.0.0.0 --port 80
    volumes:
      - ./frontend:/app

  nginx:
    image: nginx:latest
    ports:
      - ${PORT:-8080}:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
