version: '3.9'

services:
  backend:
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/go/src/github.com/koyashiro/postgres-playground

  frontend:
    build:
      context: frontend
      target: development
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    ports:
      - ${PORT:-8080}:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  node_modules:
