version: '3.9'

services:
  backend:
    build:
      context: backend
      target: development
    command: air
    volumes:
      - ./backend:/go/src/github.com/koyashiro/postgres-playground
    ports:
      - ${PORT:-8080}:80
